[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
leptos_meta = { version = "0.8" }
leptos_router = { version = "0.8" }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"

# utils
# strum = { version = "0.25", features = ["derive", "strum_macros"] }
# strum_macros = "0.25"


[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = ["Document", "Window"] }

[profile.dev]
incremental = true
opt-level = 0
debug = 1          # Reduce debug info
lto = false

[profile.dev.package."*"]
opt-level = 3 # optimize dependencies aggressively
debug = 1     # we don’t need much debug info for dependencies

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
