[template]
ignore = ["Cargo.lock", "switch_nightly_stable.rhai"]
exclude = ["public/favicon.ico"]

[placeholders]
default_channel = { prompt = "Use stable or nightly channel?", choices = [
    "stable",
    "nightly",
], default = "stable", type = "string" }
rust_analyzer_settings = { prompt = "Override `rustfmt` with `leptosfmt`?", default = false, type = "bool" }

[conditional.'rust_analyzer_settings == false']
ignore = ["rust-analyzer.toml"]

[hooks]
pre = ["switch_nightly_stable.rhai"]
